//保存用户数据
const SAVE_USERINFO = 'SAVE_USERINFO'
//保存用户信息
const SAVE_ATTRINFO = 'SAVE_ATTRINFO'
//修改用户信息
const MODIFY_USERINFO = 'MODIFY_USERINFO'
export {
    SAVE_USERINFO,
    SAVE_ATTRINFO,
    MODIFY_USERINFO
}